[package]
name = "Iris"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
display-info = "0.5.7"
mouse-rs = "0.4.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
